version: "3.8"
services:
  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_NAME=grocery
      - DB_PASSWORD=yourPass
      - DB_PORT=3306
      - DB_TYPE=mysql
      - DB_USER=root
      - PORT=3001
      
    depends_on:
      - db
    
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourPass
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: yourPass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
